# Generated by Django 5.2.1 on 2025-05-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0004_remove_members_id_alter_members_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='members',
            name='roll',
            field=models.CharField(max_length=50),
        ),
    ]
